language: python
python:
  - 2.7
sudo: false
install:
  - pip install jinja2 PyYAML tweepy
script: |
  build/build && \
  if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then build/upload; fi && \
  if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then build/tweet; fi && \
  if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TOKEN_TRAVIS" -d '{"request": {"branch": "master", "message": "reproducibility-news updated"}}' https://api.travis-ci.org/repo/ViDA-NYU%2Freproducible-science/requests; fi
notifications:
  email:
    recipients:
      - secure: "H//INg/1PnP/02Gem4eiRY8G4Lk+Df3q4HH3IC3SWXtOghRWW46Y6aV08ReC4DvBEEKy25KLnbOy229BnIvMFyQAI1I63Tt0f37Ix8pca+f7uZkk2hvKZsj2l4F32Mz+clrH8Q4P1EoPFXrIywudJjqFFXvQF6SxQ9o3gn2GOZidX54VCHUWYvvRPAigDpsqNRXZVP92405kQt5MMH+MG5PKMb19TIJ4WvY033a3M+kjn4TYzhNNiLTAQjpA30axccOFQGY7jEXSb25FIlCftaixcS/pFzqYMaUrstYmYUDb3iUtSikwmfq1zJTJPC7ZtN2Zg3Jn0aj66W2jxPJZu3OyKNpHUlCGUyqIuMY2coyCbWOfypjQ5qtQuGe31AMebXi3Ccm9DK5mdzeEp6lf1z1TccIoXRF58iYsA8aK3tchEZDAssYKw10VkuoyFO/PoeQw4v5IbZ4BGhk7Xvlvx6hn4rfPjey8+4DKfKky07DHJ84FYV/5/Wmkn1qPM+pbJ84+eGdwOUHoSfYz8aUlWh4Hsfomi6WCX9CUzBTCjxKcRlDKj+OEX1d7G+GTjH/oMXNDJ7fNDWYtHlv53x1Yd4t5+iZBkPb2IL8//wQIqHdUq6Jg5Nl5lPCpO5is5ISQ1wXZOpTco+qYGuSwzg5K43aNa/mxYDE4lrHzbD+563U="
      - secure: "puOpiqFmaekSFlzbbgO4HPLBZSDV1oY4aC+tvfDBmEPKQWz/mBGpV57tp0cmphRQHL8aL7Btbi+jHVjXNBqt9sRI31jk0PFYpXb4p7SgaZbByAy31YQTW5NFXBDxEvc7avk0XHcUZ9l2uNSrzvW4A5bms/d7E9BnB9+S1GAucvnPoj8EFKKQnLNicxAQGJe5ITMxqe6pwGaRtZXSDnXq1eUqDOyx+RI/Fc4D3rBoBVX6M7gDhKU5GbyTHb4WNe9rUcgLkqN5b0zagoTeuSIKaO/e70cAIXQZEaHppNdRC5Sgbb5QQWS7P8RFIVhuia8rzWeSVPMI8p9ZXe9Aox4f9FAq2l6R1Y+y239HdF3cMzch84sJbVszfH0Bf0G/2kaUdvO13AJNK8p6gcMvBtimyMJpeA2DGeduW2SGDc9d4y7WRn5jvzBeukUBaJNI3rXsYxYPl52e/nbjrqLX5r/RtalD8xPFvzBiCSrNYObj0rkw4paa8t1bv4bpAOLAjF6H5wFXtVobU8R9OjnxIN1RNGVK4n6JU+G5zfkSFq7o0C0/mubPBTweBndxi7ecQmMvAIi87jF0qKvS86ur496wlhlGAX0V6LEdxEe0PEj0lDgeNX+NCLj1Bou/RhVPxRq3jbtmShKJO+JpQsh9YoUyEVuQw8jiSc5eJ7nTeL7Jsbg="
    on_success: change
    on_failure: always
