name: Build

on:
  push:
    branches:
      - trunk

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install "jinja2>=3.1,<4" "PyYAML>=6.0,<7"
      - name: Build
        run: build/build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Trigger reproduciblescience.org rebuild
        if: ${{ github.ref == 'refs/heads/trunk' }}
        run: |
          curl -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H "Bearer: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/VIDA-NYU/reproducible-science/dispatches \
            -d '{"event_type":"news"}'
